In [ ]:
# Numpy -: Numerical Python
# Scientific calculation
# Data creation 

In [1]:
import numpy as np

# array learn through numpy
# list is heterogeneous means --- different data elements --- [12,34.56,"hello"]
# array is homogeneous means --- similar data elements ---[2,3,4,5], [2.1,2.3,2.5,5.4], ["abhi", "chaudhary", "hello", "world"]

In [4]:
a = np.array([12,23,34,454])
a

array([ 12,  23,  34, 454])

In [5]:
type(a)   # type is numpy.ndarray ---- here ndarrary means n dimensional array

numpy.ndarray

In [6]:
a = np.array([12,34.34,98])
a

array([12.  , 34.34, 98.  ])

In [7]:
a = np.array([12,"a",34.34,98])
a

array(['12', 'a', '34.34', '98'], dtype='<U32')

In [ ]:
# priority -: Upcasting ---- 1. String, 2. float, 3. int

In [13]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
# Errors ---- syntax error, value error, etc

In [16]:
x = np.array([12,23,34,45], ndmin = 2)
x

array([[12, 23, 34, 45]])

In [ ]:
# shape --  return number of rows and column

In [18]:
x = np.array([12,23,34,45]) # one-d
print(x)
x.shape

[12 23 34 45]


(4,)

In [19]:
x=np.array([[1,2],[3,4]]) # two-d
print(x)
x.shape

[[1 2]
 [3 4]]


(2, 2)

In [21]:
x=np.array([[1,2,3],[3,4,5]]) # change 2d to 3d
print(x)
x.shape = (3,2)
print()
print(x)

[[1 2 3]
 [3 4 5]]

[[1 2]
 [3 3]
 [4 5]]


In [22]:
# reshape
x = np.array([[12,23,34],[45,56,67]])
print(x)
y = x.reshape(3,2)
print()
print(y)

[[12 23 34]
 [45 56 67]]

[[12 23]
 [34 45]
 [56 67]]


In [ ]:
# call with reference to class is called a method, but,
# without reference to any class to call is called a function.

In [25]:
# zeros---- initialize an array with all zeros by default float
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [26]:
x = np.zeros(5, dtype = int) # float convert into int.
x

array([0, 0, 0, 0, 0])

In [27]:
x = np.zeros((5,5), dtype = int)
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
# ones method -- initialize all elements with ones by default float.
x = np.ones(5, dtype = int)
x

array([1, 1, 1, 1, 1])

In [30]:
x = np.ones((5,5), dtype = int)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
a = np.array([1,2,3])
a.ndim

1

In [32]:
a # 1X3 - matrix dimension

array([1, 2, 3])

In [ ]:
# dimension of the matrix is rows and column.

In [33]:
# arange --- arrya of range
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
x = np.arange(30).reshape(3,5,2) # (three times -- five rows -- two column)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [36]:
a = np.arange(36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [37]:
b = a.reshape(3,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [38]:
b.ravel() # b.ravel() --  flattening of a multi-dimensional array means all multi-dimensional arrays convert into one-dimensional array.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [40]:
# example of arange --
a = np.arange(0,20,2.5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

In [41]:
# asarray -- converting list into ndarray.
x = [1,2,3]
print(type(x))

<class 'list'>


In [43]:
a = np.asarray(x)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [44]:
# dtype is provided
a = np.asarray(x, dtype = float)
print(a)

[1. 2. 3.]


In [46]:
# ndarray from tuple
x = (1,2,3)
print(type(x))
a = np.asarray(x)
print(a)
print(type(a))

<class 'tuple'>
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# ndarray from list of tuples.
x = [(1,2,3),(4,5)]
a = np.asarray(x)
print(a) # error occur

In [48]:
# Revision of String ----------------------------------------------------------------------------------------------------------
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

In [49]:
s1 = "abc123"
print(s1.isalnum()) # alpha or numeric or both 
s2 = "abc 123"
print(s2.isalnum())

True
False


In [50]:
# partition gives a tuple and split gives list.
s1 = "how are you"
s1.partition("are")

('how ', 'are', ' you')

In [51]:
s1 = "how are you"
s1.partition("how")

('', 'how', ' are you')

In [52]:
s1 = "how are you"
s1.partition("now")

('how are you', '', '')

In [53]:
# split gives list
s1 = "A@B@C@D@E@F@G"
s1.split("@")


['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [54]:
# max split concept is --
s1 = "A@B@C@D@E@F@G"
s1.split("@", 3) # means only 3 split and all as print

['A', 'B', 'C', 'D@E@F@G']

In [55]:
# Strip ----- is used for remove from startin point or ending point or both.
s1 = "***** MADRID SOFTWARE *****"
s1.lstrip("*")

' MADRID SOFTWARE *****'

In [56]:
s1 = "***** MADRID SOFTWARE *****"
s1.rstrip("*")

'***** MADRID SOFTWARE '

In [57]:
s1 = "***** MADRID SOFTWARE *****"
s1.strip("*")

' MADRID SOFTWARE '

In [61]:
s1 = "    hello    "
s1.lstrip()

'hello    '

In [62]:
s1.rstrip()

'    hello'

In [63]:
s1.strip()

'hello'

In [64]:
s1 = "abhishek"
s1.upper()

'ABHISHEK'

In [65]:
s1 = "123kg"
s1.split("kg")[0]

'123'

In [2]:
s1="123kg"
s1.strip("kg")

'123'

In [ ]:
# Matrix operations -: --------------------------------------------------------------------------------------------------
#

In [4]:
import numpy as np

In [9]:
# Sum of two matrix.
x = np.array([[12,23,34],[45,56,67],[67,78,89]])
print(x)
print()
y = np.array([[34,45,56],[67,78,89],[54,43,33]])
print(y)
print()
z = x + y
print(z)

[[12 23 34]
 [45 56 67]
 [67 78 89]]

[[34 45 56]
 [67 78 89]
 [54 43 33]]

[[ 46  68  90]
 [112 134 156]
 [121 121 122]]


In [8]:
# transpose
x = np.array([[12,23,34],[45,56,67]])
print(x)
print()
y = np.transpose(x)
print(y)

[[12 23 34]
 [45 56 67]]

[[12 45]
 [23 56]
 [34 67]]


In [10]:
# Matrix multiplication ----- for multiply use (.dot())
a = np.array([[12,23],[45,56]])
print(a)
print()
b = np.array([[34,45],[56,67]])
print(b)
print()
c = np.dot(a,b)
print(c)

[[12 23]
 [45 56]]

[[34 45]
 [56 67]]

[[1696 2081]
 [4666 5777]]


In [11]:
# Matrix Concatenation -- horizontal adding example 1 -- hstack always adding next to next.
x = np.array([[12,23],[45,67]])
print(x)
print()
y = np.array([[67,78],[65,54]])
print(y)
print()
print(np.hstack((x,y)))

[[12 23]
 [45 67]]

[[67 78]
 [65 54]]

[[12 23 67 78]
 [45 67 65 54]]


In [14]:
# example 2 --- horizontal 
x = np.array([[12],[34],[98]])
print(x)
print()
y = np.array([[34],[56],[78]])
print(y)
print()
print(np.hstack((x,y)))


[[12]
 [34]
 [98]]

[[34]
 [56]
 [78]]

[[12 34]
 [34 56]
 [98 78]]


In [15]:
# Matrix Concatenation -- verticle adding example 1 -- vstack always adding down to next.
x = np.array([[12,23],[45,67]])
print(x)
print()
y = np.array([[67,78],[65,54]])
print(y)
print()
print(np.vstack((x,y)))

[[12 23]
 [45 67]]

[[67 78]
 [65 54]]

[[12 23]
 [45 67]
 [67 78]
 [65 54]]


In [16]:
# example 2 --- verticle
x = np.array([[12],[34],[98]])
print(x)
print()
y = np.array([[34],[56],[78]])
print(y)
print()
print(np.vstack((x,y)))

[[12]
 [34]
 [98]]

[[34]
 [56]
 [78]]

[[12]
 [34]
 [98]
 [34]
 [56]
 [78]]


In [18]:
# alternative ----- vstack 
x = np.array([[12],[34],[98]])
print(x)
print()
y = np.array([[34],[56],[78]])
print(y)
print()
print(np.concatenate((x,y),axis=0)) # axis = 0 means rows vstack.

[[12]
 [34]
 [98]]

[[34]
 [56]
 [78]]

[[12]
 [34]
 [98]
 [34]
 [56]
 [78]]


In [19]:
x = np.array([[12],[34],[98]])
print(x)
print()
y = np.array([[34],[56],[78]])
print(y)
print()
print(np.concatenate((x,y),axis=1)) # axis = 1 means columns hstack

[[12]
 [34]
 [98]]

[[34]
 [56]
 [78]]

[[12 34]
 [34 56]
 [98 78]]


In [20]:
a = np.array([[12,23,34,45,56],[12,23,34,45,56],[12,23,34,45,56],[12,23,34,45,56],[12,23,34,45,56]])
print(a)

[[12 23 34 45 56]
 [12 23 34 45 56]
 [12 23 34 45 56]
 [12 23 34 45 56]
 [12 23 34 45 56]]


In [23]:
# Accessing this matrix --- Indexing.
a[1:3,2:4]

array([[34, 45],
       [34, 45]])

In [24]:
x = np.array([[12,23,34],[76,65,54],[76,89,87]])
print(x)

[[12 23 34]
 [76 65 54]
 [76 89 87]]


In [25]:
x.max()

89

In [26]:
x.max(axis=1) # row max

array([34, 76, 89])

In [27]:
x.max(axis=0) # column max

array([76, 89, 87])

In [28]:
# One-d array.
x = np.array([12,23,34,45,56,65,34,98,23,12])
x.max()

98

In [29]:
x.argmax() # index of max element

7

In [30]:
x.argmin() # index of min element

0

In [33]:
x.sort()

In [34]:
x

array([12, 12, 23, 23, 34, 34, 45, 56, 65, 98])

In [35]:
x.argsort() # indexes of sorted elements

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [39]:
# Random number generation -------------------------------------------------------------------------------
x = np.random.randint(0,10) # generate integer number
x

3

In [41]:
x = np.random.rand () # random number between zero and one
x

0.47372508643283295

In [42]:
x = np.random.randint(0,10,5) # many random numbers
x

array([9, 3, 4, 4, 7])

In [43]:
x = np.random.rand(5)
x

array([0.77202377, 0.22663867, 0.17284442, 0.80200698, 0.24992335])

In [44]:
x = np.random.randint(100,200,(5,5)) # matrix
x

array([[188, 168, 176, 197, 174],
       [155, 171, 160, 141, 189],
       [181, 106, 146, 161, 123],
       [152, 137, 152, 152, 167],
       [105, 195, 171, 152, 145]])

In [45]:
from numpy.random import randint as ri # easy way of random number gerenration. 

In [46]:
x = ri(12,45,6) # here ri covers all lines of the random number method.
x

array([24, 24, 27, 13, 25, 40])

In [47]:
np.random.seed(7000) # to fix the numbers once generated
x = np.random.randint(100,200,(5,5))
x

array([[101, 163, 197, 131, 107],
       [121, 103, 194, 139, 111],
       [121, 156, 195, 139, 199],
       [190, 110, 145, 141, 186],
       [154, 102, 132, 105, 110]])

In [1]:
x = np.array([12,23,34,56,54,8,77,5,4,6])
np.random.choice(x)

NameError: name 'np' is not defined

In [ ]:
# seed means to fix the number 

In [ ]:
# Revision ----------------------------------------------------------------------------------------

In [54]:
# append() function --- It is used to insert one element in the list at a time.
# inserted value always at the end
x = [12,23,34,45]
x.append("Abhishek")
x

[12, 23, 34, 45, 'Abhishek']

In [55]:
x = [12,23,25,45,44]
x.append([45,58,87,86])
x

[12, 23, 25, 45, 44, [45, 58, 87, 86]]

In [56]:
x = [12,23,25,45] # Interview questions ---  here we give indexing 1 to 3 means go to only 2index but here add himanshu
x[1:3] = ["Abhishek","Abuzar","Himanshu"]
x

[12, 'Abhishek', 'Abuzar', 'Himanshu', 45]

In [57]:
# pop, insert, reverse, sort

x = [12,23,34,45,56,67,78,89,90]
x.pop() # remove last element
print(x)
x.pop()
print(x)

[12, 23, 34, 45, 56, 67, 78, 89]
[12, 23, 34, 45, 56, 67, 78]


In [58]:
# insert
x = [12,23,34,45,56,67,78,89,90]
x.insert(3,"Prashant")
x

[12, 23, 34, 'Prashant', 45, 56, 67, 78, 89, 90]

In [59]:
# sort -- In ascending order
x = [12,23,34,45,56,67,78,89,90]
x.sort()
x

[12, 23, 34, 45, 56, 67, 78, 89, 90]

In [60]:
# sort -- In decending order
x = [12,23,34,45,56,67,78,89,90]
x.sort(reverse=True)
x

[90, 89, 78, 67, 56, 45, 34, 23, 12]

In [61]:
# there are two methods --- sort and sorted
x.sort() # change in existing or original 
x

[12, 23, 34, 45, 56, 67, 78, 89, 90]

In [62]:
sorted(x) # create a copy.

[12, 23, 34, 45, 56, 67, 78, 89, 90]

In [ ]:
# class ----------------------

In [1]:
import numpy as np

In [3]:
# print counting 1 to 20 in array.
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
# print false and true if a is greater than 10.
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
# print values that are greater than 10 in array.
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
# print values that are less than 10 in array.
a[a < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# print even numbers.
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
# print odd numbers
a[a%2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [9]:
a[a==5] # collection of similar element. upcasting

array([5])

In [10]:
a[a<5]

array([1, 2, 3, 4])

In [11]:
a = np.array([1,2,3,4,5,2])
print(a)

[1 2 3 4 5 2]


In [12]:
a.ndim

1

In [13]:
a.shape #(6,)

(6,)

In [14]:
x = np.where(a==2) # where returns index
x

(array([1, 5], dtype=int64),)

In [15]:
np.where(a==3) # where is use for find the index of the element.

(array([2], dtype=int64),)

In [16]:
b = np.array([1,2,3,4,5,6])
print(b)

[1 2 3 4 5 6]


In [17]:
np.where(b<4)

(array([0, 1, 2], dtype=int64),)

In [18]:
np.where(b>5)

(array([5], dtype=int64),)

In [ ]:
# here sir says about generate certificate --- 2 certificate --> first is upload in linkedIn and Second which you will take with you.

In [19]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
type(x)

numpy.ndarray

In [21]:
x[-1]

10

In [22]:
# This array attribute returns the length of each element of the array in bytes.
x.itemsize # Size of integer in memory 4 bytes(compiler)--8bytes.

4

In [24]:
x = np.linspace(2,3,4)
x

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [25]:
a = np.logspace(2, 3, num=4)
a

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [26]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
a.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [29]:
a.T # short form of transpose.

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [30]:
x = np.arange(9).reshape(1,3,3)
x

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [31]:
a = np.arange(12)
np.split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [35]:
a = np.array([[1,2,3],[4,5,6]])
np.resize(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
a = np.array([[1,2,3],[4,5,6]])
b = np.append(a,[[7,8,9]])
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# TRIGONOMETRIC FUNCTION

In [38]:
I = np.eye(2,dtype=int) # Identity matrix, here diagonal is one and all the rest are zeros.
I

array([[1, 0],
       [0, 1]])

In [39]:
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]
np.matmul(a,b) # matmul is used for multiplication of two matrix.

array([[4, 1],
       [2, 2]])

In [40]:
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]
np.dot(a,b) # used for multiplication of two matrix.

array([[4, 1],
       [2, 2]])